
```{r}
library(gtools)
library(ggplot2)
library(ggsci)
library(tidyverse)
library(gridExtra)
library(scales)
library(ggsignif)
library(dplyr)
library(mice)
rm(list=ls())

data <- read.csv('C:/Users/cmorc/OneDrive - Harvard University/Projects/Metabolic Aging Atlas/C.-elegans-Mitochondrial-Aging/HM LM Analysis/FLIM_Mito_LLSL.csv')

setwd("C:/Users/cmorc/OneDrive - Harvard University/Projects/Metabolic Aging Atlas/C.-elegans-Mitochondrial-Aging/HM LM Analysis/")

data$tm <- ((data$a1 * data$t1)+((1-data$a1) * data$t2))

data$a1s <- scale(data$a1)
data$t1s <- scale(data$t1)
data$t2s <- scale(data$t2)
data$is <- scale(log(data$i))

```

##Plot Intensity##
```{r}
pdf(paste(Sys.Date()," I.pdf"))
ggplot(data=data, aes(x=Group, y=i, col=Group))+
  geom_signif(comparisons = list(c("HM","LM")), col="black", map_signif_level = TRUE, size=1, textsize=20)+
  geom_violin(size=1)+
  stat_summary(fun.data="mean_cl_boot", size=1)+
  theme_classic(base_size = 20, base_family = "")+
  theme(legend.position = "none")+
  ylab(bquote("B.A./NAD(P)H  Intensity"))+
  xlab(element_blank())+
  theme(aspect.ratio=1)+
  ylim(0,40000)+
  theme(text=element_text(size=40)) 
dev.off()
```

####Plot tm##
```{r}
pdf(paste(Sys.Date()," tm.pdf"))
  ggplot(data=data, aes(x=Group, y=tm, col=Group))+
  geom_violin(size=1)+
    geom_signif(comparisons = list(c("HM","LM")), col="black", map_signif_level = TRUE, size=1, textsize=20)+
  stat_summary(fun.data="mean_cl_boot", size=1)+
  theme_classic(base_size = 20, base_family = "")+
  theme(legend.position = "none")+
  ylab(bquote("B.A./NAD(P)H  " *tau[m]* " (ns)"))+
  xlab(element_blank())+
  theme(aspect.ratio=1)+
   ylim(1,3.5)+
  theme(text=element_text(size=40))
dev.off()
```

##Plot a1##
```{r}
pdf(paste(Sys.Date()," a1.pdf"))
  ggplot(data=data, aes(x=Group, y=a1, col=Group))+
    geom_signif(comparisons = list(c("HM","LM")), col="black", map_signif_level = TRUE, size=1, textsize=20)+
  geom_violin(size=1)+
  stat_summary(fun.data="mean_cl_boot", size=1)+
  theme_classic(base_size = 20, base_family = "")+
  theme(legend.position = "none")+
  ylab(bquote("B.A./NAD(P)H  " *alpha[1]* " (ns)"))+
  xlab(element_blank())+
  theme(aspect.ratio=1)+
   ylim(0.5,1)+
  theme(text=element_text(size=40))
dev.off()

```
##Plot t1##
```{r}
pdf(paste(Sys.Date()," t1.pdf"))
ggplot(data=data, aes(x=Group, y=t1, col=Group))+
geom_violin(size=1)+
geom_signif(comparisons = list(c("HM","LM")), col="black", map_signif_level = TRUE, size=1, textsize=20)+
stat_summary(fun.data="mean_cl_boot", size=1)+
theme_classic(base_size = 20, base_family = "")+
theme(legend.position = "none")+
ylab(bquote("B.A./NAD(P)H  " *tau[1]* " (ns)"))+
xlab(element_blank())+
theme(aspect.ratio=1)+
ylim(0.3,1)+
theme(text=element_text(size=40))
dev.off()
```


##Plot t2##
```{r}
pdf(paste(Sys.Date()," t2.pdf"))
ggplot(data=data, aes(x=Group, y=t2, col=Group))+
  geom_violin(size=1)+
    geom_signif(comparisons = list(c("HM","LM")), col="black", map_signif_level = TRUE, size=1, textsize=20)+
  stat_summary(fun.data="mean_cl_boot", size=1)+
  theme_classic(base_size = 20, base_family = "")+
  theme(legend.position = "none")+
  ylab(bquote("B.A./NAD(P)H  " *tau[2]* " (ns)"))+
  xlab(element_blank())+
  theme(aspect.ratio=1)+
  ylim(2.5,6)+
  theme(text=element_text(size=40)) 
dev.off()
```


##PCA NOT NOT WITH Y O##
```{r}
data_lmhm <- read.csv('C:/Users/cmorc/OneDrive - Harvard University/Projects/Metabolic Aging Atlas/C.-elegans-Mitochondrial-Aging/HM LM Analysis/FLIM_Mito_LLSL.csv')

data_mito_animal <- read.csv('C:/Users/cmorc/OneDrive - Harvard University/Projects/Metabolic Aging Atlas/C.-elegans-Mitochondrial-Aging/FLIM_Mito_Median_Per_Animal_052623.csv')

myages_yo <- c("1","11")
mytissues_mus <- "Caudal BWM"
mynutrients_al <- "WT"

data_mito_animal_yo_caudaulbwm_wt <- subset(data_mito_animal, Nutrients%in%mynutrients_al)
data_mito_animal_yo_caudaulbwm_wt <- subset(data_mito_animal_yo_caudaulbwm_wt, TissueFullName%in%mytissues_mus)
data_mito_animal_yo_caudaulbwm_wt <- subset(data_mito_animal_yo_caudaulbwm_wt, Age%in%myages_yo)
data_mito_animal_yo_caudaulbwm_wt$Group <- as.character(data_mito_animal_yo_caudaulbwm_wt$Age)
myvars <- c("a1","t1","t2","i","Group")
data_mito_animal_yo_caudaulbwm_wt <- data_mito_animal_yo_caudaulbwm_wt[myvars]

data_merge <- rbind(data_lmhm, data_mito_animal_yo_caudaulbwm_wt)

data_merge$a1 <- scale(data_merge$a1)
data_merge$t1 <- scale(data_merge$t1)
data_merge$t2 <- scale(data_merge$t2)
data_merge$i <- scale(data_merge$i)

data_merge[data_merge == "1"] <- "Young"
data_merge[data_merge == "11"] <- "Old"

pca <- prcomp(data_merge[,1:4], scale=TRUE)

pcadata <- data.frame(pca$x[,1], pca$x[,2], Group=data_merge$Group)

pdf(paste(Sys.Date()," pca not with y o.pdf"))
ggplot(pcadata, aes(x=pca$x[,1], y=pca$x[,2], col=Group))+
geom_point(size = 3)+
theme_classic(base_size = 25, base_family = "")+
ylab(bquote("PC2"))+
xlab(bquote("PC1"))+
theme(aspect.ratio = 1)
dev.off()
```








