
```{r}
library(gtools)
library(ggplot2)
library(ggsci)
library(tidyverse)
library(gridExtra)
library(scales)
library(cluster)
library(stringr)
library(ggsignif)
rm(list=ls())


data_mito_animal_matrix <- read.csv('C:/Users/cmorc/OneDrive - Harvard University/Projects/Metabolic Aging Atlas/Data Analysis/FLIM_Mito_Median_Per_Animal_Animal_Matrix_052623.csv')

setwd('C:/Users/cmorc/OneDrive - Harvard University/Projects/Metabolic Aging Atlas/Data Analysis/Tissue Analyses/WT Aging Analyses')

data_mito_animal_matrix$Condition <- str_c(data_mito_animal_matrix$Age," ",data_mito_animal_matrix$Nutrients)

mynutrients <- c("AL")
data_al <- as.data.frame(subset(data_mito_animal_matrix, Nutrients%in%mynutrients))

myages <- c("1","11")
#myages <- c("1","3","5","7","9","11")
#myages <- c("One","Three","Five","Seven","Nine","Eleven")
data_al_youngold <- as.data.frame(subset(data_al, Age%in%myages))

data_al_youngold$Age <- as.character(data_al_youngold$Age)
data_al_youngold_musNAremov <- data_al_youngold[data_al_youngold$t.bwm.tm != "#N/A", ] 
data_al_youngold_hypNAremov <- data_al_youngold[data_al_youngold$t.h.tm != "#N/A", ] 
data_al_youngold_pmNAremov <- data_al_youngold[data_al_youngold$pm.tm != "#N/A", ] 
data_al_youngold_germNAremov <- data_al_youngold[data_al_youngold$g.tm != "#N/A", ] 



```


##Plot tm y vs o mus##
```{r}
data_al_youngold_musNAremov$t.bwm.tm <- as.numeric(data_al_youngold_musNAremov$t.bwm.tm)

pdf("tm y vs o bwm.pdf")
  ggplot(data=data_al_youngold_musNAremov, aes(x=Age, y=t.bwm.tm, color=Age))+
    geom_violin(color="black")+
    geom_signif(comparisons = list(c("1","11")), col="black", map_signif_level = TRUE, size=1, textsize=20)+
  stat_summary(fun.data="mean_cl_boot", size=1, color="black")+
  theme_classic(base_size = 30, base_family = "")+
  #theme(legend.position = "none")+
  ylab(bquote("B.A./NAD(P)H " *tau* "m (ns)"))+
  xlab("Age (Days)")+
    ylim(1,5)+
    ggtitle("BWM")+
  theme(aspect.ratio=1)
#dev.off()

```


##Plot tm y vs o hyp##
```{r}




data_al_youngold_hypNAremov$t.h.tm <- as.numeric(data_al_youngold_hypNAremov$t.h.tm)

pdf("tm y vs o hyp.pdf")
  ggplot(data=data_al_youngold_hypNAremov, aes(x=Age, y=t.h.tm, color="black"))+
        geom_signif(comparisons = list(c("1","11")), col="black", map_signif_level = TRUE, size=1, textsize=20)+
    geom_violin(color="black")+
  stat_summary(fun.data="mean_cl_boot", size=1, color="black")+
  theme_classic(base_size = 30, base_family = "")+
  #theme(legend.position = "none")+
  ylab(bquote("B.A./NAD(P)H " *tau* "m (ns)"))+
  xlab("Age (Days)")+
    ggtitle("Hypodermis")+
     ylim(1,5)+
  theme(aspect.ratio=1)
dev.off()

```

##Plot tm y vs o pm##
```{r}
data_al_youngold_pmNAremov$pm.tm <- as.numeric(data_al_youngold_pmNAremov$pm.tm)

pdf("tm y vs o pm.pdf")
  ggplot(data=data_al_youngold_pmNAremov, aes(x=Age, y=pm.tm, color="black"))+
    geom_violin(color="black")+
  stat_summary(fun.data="mean_cl_boot", size=1, color="black")+
  theme_classic(base_size = 30, base_family = "")+
  #theme(legend.position = "none")+
        geom_signif(comparisons = list(c("1","11")), col="black", map_signif_level = TRUE, size=1, textsize=20)+
  ylab(bquote("B.A./NAD(P)H " *tau* "m (ns)"))+
    ylim(1,5)+
  xlab("Age (Days)")+
    ggtitle("PM")+
  theme(aspect.ratio=1)
dev.off()

```

##Plot tm y vs o germ##
```{r}


myagesgerm <- c("1","9")
data_al_youngoldgerm <- as.data.frame(subset(data_al, Age%in%myagesgerm))
data_al_youngoldgerm_germNAremov <- data_al_youngoldgerm[data_al_youngoldgerm$g.tm != "#N/A", ] 
data_al_youngoldgerm_germNAremov$g.tm <- as.numeric(data_al_youngoldgerm_germNAremov$g.tm)
data_al_youngoldgerm_germNAremov$Age <- as.character(data_al_youngoldgerm_germNAremov$Age)

pdf("tm y vs o germ.pdf")
  ggplot(data=data_al_youngoldgerm_germNAremov, aes(x=Age, y=g.tm, color="black"))+
    geom_violin(color="black")+
  stat_summary(fun.data="mean_cl_boot", size=1, color="black")+
  theme_classic(base_size = 30, base_family = "")+
  #theme(legend.position = "none")+
        geom_signif(comparisons = list(c("1","9")), col="black", map_signif_level = TRUE, size=1, textsize=20)+
  ylab(bquote("B.A./NAD(P)H " *tau* "m (ns)"))+
  xlab("Age (Days)")+
    ylim(1,5)+
    ggtitle("Germline")+
  theme(aspect.ratio=1)
dev.off()

```
