
##Read in data, clear workspace and load packages
```{r}
library(gtools)
library(ggplot2)
library(ggsci)
library(tidyverse)
library(gridExtra)
library(scales)
library(cluster)
library(stringr)
rm(list=ls())

setwd('C:/Users/cmorc/OneDrive - Harvard University/Projects/Metabolic Aging Atlas/Data Analysis/WT Aging Analyses/')

data_mito <- read.csv('C:/Users/cmorc/OneDrive - Harvard University/Projects/Metabolic Aging Atlas/Data Analysis/FLIM_Mito_052623.csv')

data_mito_animal <- read.csv('C:/Users/cmorc/OneDrive - Harvard University/Projects/Metabolic Aging Atlas/Data Analysis/FLIM_Mito_Median_Per_Animal_052623.csv')

data_mito_animal_matrix <- read.csv('C:/Users/cmorc/OneDrive - Harvard University/Projects/Metabolic Aging Atlas/Data Analysis/FLIM_Mito_Median_Per_Animal_Animal_Matrix_052623.csv')

```

##Process data for time course plots
```{r}
mytissues_4 <- c("PM", "Caudal BWM", "Caudal Hypodermis","Germline")
mynutrients_al <- c("AL")

data_4tissues <- as.data.frame(subset(data_mito_animal, TissueFullName%in%mytissues_4))
data_4tissues <- as.data.frame(subset(data_4tissues, Nutrients%in%mynutrients_al))
data_4tissues$Condition <- str_c(data_4tissues$Age," ", data_4tissues$Tissue," ",data_4tissues$Nutrients)

data_4tissues$Imean <- ave(data_4tissues$i, data_4tissues$Condition)
data_4tissues$a1mean <- ave(data_4tissues$a1, data_4tissues$Condition)
data_4tissues$t1mean <- ave(data_4tissues$t1, data_4tissues$Condition)
data_4tissues$t2mean <- ave(data_4tissues$t2, data_4tissues$Condition)
data_4tissues$tmmean <- ave(data_4tissues$tm,data_4tissues$Condition)
myvars2 <- c("a1mean", "t2mean", "t1mean", "Imean", "tmmean", "Condition", "Age", "Nutrients", "Tissue")
data_4tissues_averages <- unique(data_4tissues[myvars2], by ="Imean")
```


##Plot tm line##
```{r}
#pdf(paste(Sys.Date(),"tm line.pdf"))
  ggplot(data=data_4tissues_averages, aes(x=Age, y=tmmean, group=Tissue, color=Tissue))+
    geom_line(size=2)+
  theme_classic(base_size = 20, base_family = "")+
  theme(legend.position = "none")+
  ylab(bquote("B.A./NAD(P)H " *tau* "m (ns)"))+
  xlab("Age (Days)")+
  theme(aspect.ratio=1)+
  theme(text=element_text(size=20))+ 
    theme(legend.position="right")
#dev.off()

```


##Plot I line##
```{r}

#pdf(paste(Sys.Date(),"I line.pdf"))
  ggplot(data=data_4tissues_averages, aes(x=Age, y=Imean, group=Tissue, color=Tissue))+
    geom_line(size=2)+
  #stat_summary(fun.data_4tissues="mean_cl_boot", size=1)+
  theme_classic(base_size = 20, base_family = "")+
  theme(legend.position = "none")+
  ylab(bquote("B.A./NAD(P)H  Intensity"))+
  xlab("Age (Days)")+
  theme(aspect.ratio=1)+
  theme(text=element_text(size=20))+ 
    theme(legend.position="right")+
    ylim(0,15000)
  #theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))+
  #ggtitle(mytissues)
#dev.off()

```

##Plot a1 line##
```{r}
#pdf(paste(Sys.Date(),"I line.pdf"))
  ggplot(data=data_4tissues_averages, aes(x=Age, y=a1mean, group=Tissue, color=Tissue))+
    geom_line(size=2)+
  #stat_summary(fun.data_4tissues="mean_cl_boot", size=1)+
  theme_classic(base_size = 20, base_family = "")+
  theme(legend.position = "none")+
  ylab(bquote("B.A./NAD(P)H  " *alpha[1]* " (ns)"))+
  xlab("Age (Days)")+
  theme(aspect.ratio=1)+
  theme(text=element_text(size=20))+ 
    theme(legend.position="right")
  #theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))+
  #ggtitle(mytissues)
#dev.off()

```

##Plot t1 line##
```{r}
#pdf(paste(Sys.Date(),"t1 line.pdf"))
  ggplot(data=data_4tissues_averages, aes(x=Age, y=t1mean, group=Tissue, color=Tissue))+
    geom_line(size=2)+
  #stat_summary(fun.data_4tissues="mean_cl_boot", size=1)+
  theme_classic(base_size = 20, base_family = "")+
  theme(legend.position = "none")+
   ylab(bquote("B.A./NAD(P)H  " *tau[1]* " (ns)"))+
  xlab("Age (Days)")+
  theme(aspect.ratio=1)+
  theme(text=element_text(size=20))+ 
    theme(legend.position="right")+
    ylim(0,1)
  #theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))+
  #ggtitle(mytissues)
#dev.off()

```

##Plot t2 line##
```{r}
#pdf(paste(Sys.Date(),"t2 line.pdf"))
  ggplot(data=data_4tissues_averages, aes(x=Age, y=t2mean, group=Tissue, color=Tissue))+
    geom_line(size=2)+
  #stat_summary(fun.data="mean_cl_boot", size=1)+
  theme_classic(base_size = 20, base_family = "")+
  theme(legend.position = "none")+
   ylab(bquote("B.A./NAD(P)H  " *tau[2]* " (ns)"))+
  xlab("Age (Days)")+
  theme(aspect.ratio=1)+
  theme(text=element_text(size=20))+ 
    theme(legend.position="right")
  #theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))+
  #ggtitle(mytissues)
#dev.off()

```

##Normalize Data for PCA
```{r}
##Normalize data set##
data_mito_norm <- data.frame(scale(data_mito$a1), scale(data_mito$t1), scale(data_mito$t2), scale(log(data_mito$i)), data_mito$Age, data_mito$Tissue, data_mito$Nutrients, data_mito$TissueFullName)
```

##PCA ggplot Muscle##
```{r}
set.seed(1)
mytissuesm <- c("Caudal BWM")
mynutrients_al <- c("AL")

datamus <- as.data.frame(subset(data_mito_norm, data_mito.TissueFullName%in%mytissuesm))
datamus <- as.data.frame(subset(datamus, data_mito.Nutrients%in%mynutrients_al))
myvars3 <- c("scale.data_mito.a1.","scale.data_mito.t1.","scale.data_mito.t2.","scale.log.data_mito.i..","data_mito.Age")
datamus <- datamus[myvars3]

pca <- prcomp(datamus[,1:4], scale=TRUE)
pca.var <- pca$sdev^2
pca.var.per <- round(pca.var/sum(pca.var)*100, 1)

pcadata <- data.frame(pca$x[,1], pca$x[,2], Age=datamus$data_mito.Age)
pcadata

mid<-mean(datamus$data_mito.Age)

#pdf(paste(Sys.Date(), " BWM PCA.pdf"))
ggplot(pcadata, aes(x=pca$x[,1], y=pca$x[,2], col=Age))+
  scale_color_gradient2(midpoint=mid, low="cyan", mid="blue",high="red", space ="Lab")+
  geom_point(size = 2)+
  theme_classic(base_size = 20, base_family = "")+
  ylab(bquote("PC2"))+
  xlab(bquote("PC1"))+
  theme(aspect.ratio = 1)+
  ggtitle("BWM")+
#dev.off()

pca.one <- pcadata[pcadata$Age == "1",]
sd.one.pca.one <- sd(pca.one[,1])

pca.three <- pcadata[pcadata$Age == "3",]
sd.one.pca.three <- sd(pca.three[,1])

pca.five <- pcadata[pcadata$Age == "5",]
sd.one.pca.five <- sd(pca.five[,1])

pca.seven <- pcadata[pcadata$Age == "7",]
sd.one.pca.seven <- sd(pca.seven[,1])

pca.nine <- pcadata[pcadata$Age == "9",]
sd.one.pca.nine <- sd(pca.nine[,1])

pca.eleven <- pcadata[pcadata$Age == "11",]
sd.one.pca.eleven <- sd(pca.eleven[,1])

pca.sds <- c(sd.one.pca.one, sd.one.pca.three, sd.one.pca.five, sd.one.pca.seven, sd.one.pca.nine, sd.one.pca.eleven)
pca.sds.mus <- c(sd.one.pca.one, sd.one.pca.three, sd.one.pca.five, sd.one.pca.seven, sd.one.pca.nine, sd.one.pca.eleven)
tissue.names <- c(1,3,5,7,9,11)

pca.sds.with.title <- as.data.frame(pca.sds, tissue.names)
pca.sds.with.title$titles <- tissue.names
```

##PCA ggplot Hyp##
```{r}
set.seed(1)
mytissuesh <- c("Caudal Hypodermis")
datahyp <- as.data.frame(subset(data_4tissues, TissueFullName%in%mytissuesh))
myvars3 <- c("a1","t1","t2","i","Age")
datahyp <- datahyp[myvars3]

pca <- prcomp(datahyp[,1:4], scale=TRUE)
pca.var <- pca$sdev^2
pca.var.per <- round(pca.var/sum(pca.var)*100, 1)

pcadata <- data.frame(pca$x[,1], pca$x[,2], Age=datahyp$Age)

mid<-mean(datahyp$Age)

#pdf(paste(Sys.Date(), "Hypodermis PCA.pdf"))
ggplot(pcadata, aes(x=pca$x[,1], y=pca$x[,2], col=Age))+
  scale_color_gradient2(midpoint=mid, low="cyan", mid="blue",high="red", space ="Lab")+
  geom_point(size = 2)+
  #stat_summary(fun.data="mean_cl_boot", size=1)+
  theme_classic(base_size = 20, base_family = "")+
  #scale_color_manual(values=colors)+
  #theme(legend.position = "none")+
  ylab(bquote("PC2"))+
  xlab(bquote("PC1"))+
  #theme(aspect.ratio=1)+
  #theme(text=element_text(size=20))+                               
  theme(aspect.ratio = 1)+
  ggtitle("Hypodermis")#+
  #theme(plot.title = element_text(hjust = 0.5))+
  #geom_text(data=graphLabels, aes(x=Group, y = c(max+.2), label=Pval), size=10, color="black")
#dev.off()

pca.one <- pcadata[pcadata$Age == "1",]
sd.one.pca.one <- sd(pca.one[,1])

pca.three <- pcadata[pcadata$Age == "3",]
sd.one.pca.three <- sd(pca.three[,1])

pca.five <- pcadata[pcadata$Age == "5",]
sd.one.pca.five <- sd(pca.five[,1])

pca.seven <- pcadata[pcadata$Age == "7",]
sd.one.pca.seven <- sd(pca.seven[,1])

pca.nine <- pcadata[pcadata$Age == "9",]
sd.one.pca.nine <- sd(pca.nine[,1])

pca.eleven <- pcadata[pcadata$Age == "11",]
sd.one.pca.eleven <- sd(pca.eleven[,1])


pca.sds <- c(sd.one.pca.one, sd.one.pca.three, sd.one.pca.five, sd.one.pca.seven, sd.one.pca.nine, sd.one.pca.eleven)
pca.sds.hyp <- c(sd.one.pca.one, sd.one.pca.three, sd.one.pca.five, sd.one.pca.seven, sd.one.pca.nine, sd.one.pca.eleven)
tissue.names <- c(1,3,5,7,9,11)

pca.sds.with.title <- as.data.frame(pca.sds, tissue.names)
pca.sds.with.title$titles <- tissue.names
```

##PCA ggplot Pharyngeal Muscle##
```{r}
set.seed(1)
mytissuespm <- c("PM")
datapm <- as.data.frame(subset(data_4tissues, TissueFullName%in%mytissuespm))
myvars3 <- c("a1","t1","t2","i","Age")
datapm <- datapm[myvars3]

pca <- prcomp(datapm[,1:4], scale=TRUE)
pca.var <- pca$sdev^2
pca.var.per <- round(pca.var/sum(pca.var)*100, 1)

pcadata <- data.frame(pca$x[,1], pca$x[,2], Age=datapm$Age)
pcadata

mid<-mean(datapm$Age)

#pdf(paste(Sys.Date(), "PM PCA.pdf"))
ggplot(pcadata, aes(x=pca$x[,1], y=pca$x[,2], col=Age))+
  scale_color_gradient2(midpoint=mid, low="cyan", mid="blue",high="red", space ="Lab")+
  geom_point(size = 2)+
  #stat_summary(fun.data="mean_cl_boot", size=1)+
  theme_classic(base_size = 20, base_family = "")+
  #scale_color_manual(values=colors)+
  #theme(legend.position = "none")+
  ylab(bquote("PCA2"))+
  xlab(bquote("PCA1"))+
  #theme(aspect.ratio=1)+
  #theme(text=element_text(size=20))+                               
  theme(aspect.ratio = 1)+
  ggtitle("PM")#+
  #theme(plot.title = element_text(hjust = 0.5))+
  #geom_text(data=graphLabels, aes(x=Group, y = c(max+.2), label=Pval), size=10, color="black")
#dev.off()

pca.one <- pcadata[pcadata$Age == "1",]
sd.one.pca.one <- sd(pca.one[,1])

pca.three <- pcadata[pcadata$Age == "3",]
sd.one.pca.three <- sd(pca.three[,1])

pca.five <- pcadata[pcadata$Age == "5",]
sd.one.pca.five <- sd(pca.five[,1])

pca.seven <- pcadata[pcadata$Age == "7",]
sd.one.pca.seven <- sd(pca.seven[,1])

pca.nine <- pcadata[pcadata$Age == "9",]
sd.one.pca.nine <- sd(pca.nine[,1])

pca.eleven <- pcadata[pcadata$Age == "11",]
sd.one.pca.eleven <- sd(pca.eleven[,1])


pca.sds <- c(sd.one.pca.one, sd.one.pca.three, sd.one.pca.five, sd.one.pca.seven, sd.one.pca.nine, sd.one.pca.eleven)
pca.sds.pm <- c(sd.one.pca.one, sd.one.pca.three, sd.one.pca.five, sd.one.pca.seven, sd.one.pca.nine, sd.one.pca.eleven)
tissue.names <- c(1,3,5,7,9,11)

pca.sds.with.title <- as.data.frame(pca.sds, tissue.names)
pca.sds.with.title$titles <- tissue.names
```


##SD plot
```{r}
Age <- c(1,3,5,7,9,11)

sd.merge <- as.data.frame(Age)

sd.merge$pm <- as.vector(pca.sds.pm)
sd.merge$mus <- as.vector(pca.sds.mus)
sd.merge$hyp <- as.vector(pca.sds.hyp)


#pdf("sd merge line.pdf")
ggplot(data=sd.merge, aes(x=Age))+
  geom_line(aes(y = pm), color="#7CAE00", size=2)+
  geom_line(aes(y = mus), color="#00BFC4", size=2)+
  geom_line(aes(y = hyp), color="#C77CFF", size=2)+
  theme_classic(base_size = 20)+
  ylab(bquote("Standard Deviation PC1"))+
  xlab("Age (Days)")+
  theme(aspect.ratio=1)+
  theme(text=element_text(size=20))
#dev.off()



```

##Plot tm line for cranial vs caudal over time plot##
```{r}
mytissues_crca <- c("Cranial BWM", "Caudal BWM", "Cranial Hypodermis","Caudal Hypodermis")
mynutrients_al <- c("AL")

data3 <- as.data.frame(subset(data_mito_animal, TissueFullName%in%mytissues))
data <- as.data.frame(subset(data3, Nutrients%in%mynutrients))


data$Condition <- str_c(data$Age," ", data$TissueFullName," ",data$Nutrients)

##Normalize data set##
data_norm <- data.frame(rescale(data$a1), rescale(data$t1), rescale(data$t2), rescale(log(data$i)), data$Age, data$Tissue, data$Nutrients)

##Calculate Average Values
data$Imean <- ave(data$i, data$Condition)
data$a1mean <- ave(data$a1, data$Condition)
data$t1mean <- ave(data$t1, data$Condition)
data$t2mean <- ave(data$t2, data$Condition)
data$tmmean <- ave(data$tm,data$Condition)
myvars2 <- c("a1mean", "t2mean", "t1mean", "Imean", "tmmean", "Condition", "Age", "Nutrients", "TissueFullName")
data_averages <- unique(data[myvars2], by ="Imean")

#pdf(paste(Sys.Date(), "tm caud cran line.pdf"))
  ggplot(data=data_averages, aes(x=Age, y=tmmean, group=TissueFullName, color=TissueFullName))+
  geom_line(size=2)+
  theme_classic(base_size = 20, base_family = "")+
  theme(legend.position = "none")+
  ylab(bquote("B.A./NAD(P)H " *tau* "m (ns)"))+
  xlab("Age (Days)")+
  theme(aspect.ratio=1)+
  theme(text=element_text(size=30))+
  theme(legend.position="right")
#dev.off()

```



